// plugins/ai/image.js
export default {
  command: ['image', 'imagine', 'draw'],
  desc: 'Generate an AI image — .image <description>',
  category: 'ai',
  run: async ({ text, sock, jid, msg, reply }) => {
    if (!text) return reply('Usage: .image <description>\nExample: .image a sunset over mountains');
    await reply('🎨 *Generating image…* Please wait.');
    try {
      const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(text)}?width=512&height=512&nologo=true&seed=${Date.now()}`;
      await sock.sendMessage(
        jid,
        { image: { url }, caption: `🎨 *${text}*\n\n_Generated by RIOT AI_` },
        { quoted: msg }
      );
    } catch (e) {
      await reply('❌ Image generation failed: ' + e.message);
    }
  },
};
