// plugins/tools/namecard.js
export default {
  command: ['namecard', 'vcard', 'card'],
  desc: 'Generate a digital name card — .namecard Sydney | Developer | +254700000000',
  category: 'tools',
  run: async ({ text, reply }) => {
    if (!text) return reply('Usage: .namecard <name> | <title> | <phone> | <email>\nExample: .namecard Sydney Sider | Bot Developer | +254700000000 | sydney@email.com');
    const parts   = text.split('|').map(s => s.trim());
    const name    = parts[0] || '—';
    const title   = parts[1] || '—';
    const phone   = parts[2] || '—';
    const email   = parts[3] || '—';
    const website = parts[4] || '—';
    await reply(
      `┏━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n` +
      `┃     📇 DIGITAL NAME CARD     ┃\n` +
      `┣━━━━━━━━━━━━━━━━━━━━━━━━━━┫\n` +
      `┃\n` +
      `┃  👤 *${name}*\n` +
      `┃  💼 ${title}\n` +
      `┃\n` +
      `┃  📱 ${phone}\n` +
      `┃  📧 ${email}\n` +
      `${website !== '—' ? `┃  🌐 ${website}\n` : ''}` +
      `┃\n` +
      `┗━━━━━━━━━━━━━━━━━━━━━━━━━━┛\n\n` +
      `_Generated by RIOT MD ⚡_`
    );
  },
};
